spring:
  application:
    name: firenay-leave-redis
  redis:
#    host: 120.79.50.189
    host: 192.168.56.10

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
server:
  port: 3000